### ISSUE TITLE
State pattern

### ISSUE THREAD

**Issue by 0xLaurens** [martijnschermers/avans-devops#1]
The state pattern wasn't properly implemented according to the design pattern. This causes the code to have a extremely high cyclomatic complexity. Fix this rn!

**Comment by 0xLaurens** [comment]
@martijnschermers :cry:

**Comment by 0xLaurens** [comment]
![image](https://github.com/martijnschermers/avans-devops/assets/64641417/35f652ae-159a-45e6-84f3-9c745b5cf887)

**Comment by Luca-R04** [comment]
only serious issues @0xLaurens!!!!!!!!!!
